### ISSUE TITLE
Image won't rotate the other way when clicked

### ISSUE THREAD

**Issue by nanderspeerstra** [danielsteman/vite-blog#1]
The current image only rotates clockwise, but it doesn't rotate counterclockwise after clicking.

![image](https://user-images.githubusercontent.com/6020091/189653246-bf34807a-48af-4ff3-86b2-9ffffebdd2af.png)

**Comment by danielsteman** [comment]
Solved in d0389a16dc1f03ad3d1a31f00e9d6ab7b432d40f
